project:
  type: website
  output-dir: docs

execute:
  freeze: true

resources:
  - CNAME

website:
  title: "Familien G Damsbo"
  favicon: logo.png
  navbar:
    logo: logo.png
    logo-href: https://fam.gdamsbo.dk
    left:
      - href: index.qmd
        text: Start
      - href: food.qmd
        text: Opskrifter
      - href: https://ebba.gdamsbo.dk/
        text: Ebbas side
      # - href: blog.qmd
      #   text: Blog
    right:
      - href: https://github.com/agdamsbo/familien.gdamsbo
        text: Kildekode
  page-footer: 
    background: dark
    center: |
      Lavet med [Quarto](https://quarto.org/) i [RStudio](https://posit.co/download/rstudio-desktop/) | [Licens: CC-BY 4.0](LICENSE.html) {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}  | Statistik med [Umami](https://analytics.gdamsbo.dk/share/DXB70SBStpd77c3Y/Familie-side)


format:
  html:
    code-fold: true
    message: false
    warning: false
    code-overflow: wrap
    theme: 
      dark: solar
      light: lumen
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: umami.html
    email-obfuscation: references

editor: visual

