project:
  type: website
  output-dir: docs

resources:
  - CNAME

website:
  title: "Familien G Damsbo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: food.qmd
        text: Opskrifter
      - href: blog.qmd
        text: Blog

format:
  html:
    code-fold: true
    code-overflow: wrap
    theme: 
      dark: solar
      light: lumen
    # css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    # include-in-header: umami.html

editor: visual

