project:
  type: website
  output-dir: docs

execute:
  freeze: auto

resources:
  - CNAME

website:
  title: "Familien G Damsbo"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: food.qmd
        text: Opskrifter
      - href: blog.qmd
        text: Blog
    right:
      - href: https://github.com/agdamsbo/familien.gdamsbo
        text: Kildekode
  page-footer: 
    background: dark
    center: |
      Lavet med [Quarto](https://quarto.org/) i [RStudio]() | Statistics with [Umami](https://stats.nikohuru.dk/share/qpECsH3GvxLM5L92/fam.gdamsbo)


format:
  html:
    code-fold: true
    message: false
    warning: false
    code-overflow: wrap
    theme: 
      dark: solar
      light: lumen
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: umami.html

editor: visual

