---
title: Rugbrødsopskrift til træramme
lang: da
date: last-modified
author: Andreas
formats: 
  - pdf: default
---

## Dag 1

Tag din surdej ud og fodr den. [Se her for gode råd.](https://fam.gdamsbo.dk/food/surdej.html)

## Dag 2

-   [ ] 175 g surdej (ca. 1½ dl)
-   [ ] 30 g salt
-   [ ] 1 liter koldt vand
-   [ ] 400 g skårne rugkerner
-   [ ] 600 g rugmel

Røres sammen i en stor skål (5 L) fx på en røremaskine.

-   [ ] 300 g skårne rugkerner
-   [ ] 25 g surdej (passer for det meste med resten)
-   [ ] 4,5 dl vand

Blandes og sættes i blød (3 L).

Både dej og kerner står tildækket ved stuetemperatur i 12-36 timer.

## Dag 3

Dejen og kerner (de skal ikke drænes) fra Dag 2 blandes.

Desuden tilsættes følgende:

-   [ ] 4 dl frø (fx sesam, solsikke- og græskarkerner i forholdet 1:2:1)
-   [ ] 1 spsk honning (kan røres ud i øl)
-   [ ] 1 øl (33 cl, gerne hvidtøl eller anden mørk øl, men det kommer sig ikke så nøje)
-   [ ] Ca 9 dl rugmel til rette konsistens.
-   [ ] Evt. 2 spsk mørk maltsirup (Giver mere smag og farve)

Det hele røres godt sammen. Det skal have en tyk, sej klistret konsistens og fordeles i 3 smør-smurte trærammer der rummer 2 liter. Glat dejen.

Lad nu brødene hæve under et fugtigt viskestykke indtil dejen når til kanten (1-4 timer). Inden de bages, brug da en våd strikkepind eller lignende til at prikke huller i brødene (ca. 30 i hver), så større luftlommer punkteres.

Bages med konventionel varme ved 180°C i 1 time og 45 minutter.

Efter bagning fjernes rammerne og brødene skal køle noget af inden de lægges i plastikposer.

Vi plejer at kunne spise de tre brød i løbet af en uges tid. De holder sig længere i køleskabet, men bliver noget tørre og hårde. Egner sig også til at fryse ned, men vent to døgn. Så smuldrer brødet ikke så meget når det skæres efter optøning.
