---
title: "Super nem banankage"
date: 2023-04-28
description: Der er aldrig nok banan i banankage. Sådan er det ikke her!
categories:
  - Kage
  - Bagværk
  - Børnene med!
  - Dansk
---

## Noter

Denne kage kan sagtens røres sammen med et par unger. Der er sjovt at mose bananer og røre i dej. Dejen smager også ubagt og er jo ikke så farlig. Det tager 15-20 minutter at røre det hele sammen og det passer til en klassisk rugbrødsform på ca 3 L. Kagen er særdeles velegnet til at lægge i fryseren.

## Ingredienser

-   3-5 godt modne bananer - moses

-   200-250 ml. sukker

-   2 æg - moses m. gaffel

-   1 tsk. natron

-   5 dl. mel

-   2 dI. hakkede valnødder

-   1½ dl. olie/margarine

-   1 tsk. vanillesukker

## Sådan gør du

1.  Start med at tænde ovnen på 175 grader.

2.  Våde og tørre ingredienser blandes hver for sig.

3.  Alt blandes og røres godt sammen i en skål.

4.  Formen smøres og drysses med rasp el. mel. Alternativt beklædes den med bagepapir.

5.  Dejen hældes i formen og bages ca. 45 min. Tjek med en strikkepind at kagen er gennembagt.
