---
title: Elses vafler
lang: da
date: 2023-03-05
description: Verdens bedste vafler. Punktum.
author: Andreas
categories:
  - Kage
  - Forår
  - Børnene med!
---

## Noter

At tale om verdens bedste vafler er naturligvis lidt fjollet. Men denne opskrift er virkelig god.

Derhjemme var det et sikkert tegn på forår, når Else fandt vaffeljernene frem ude på havebordet i drivhuset og inviterede nabolagets børn over.

Der er ikke sparet på smøret, men sådan må det være. Vaflerne bliver super lækre og sprøde og er særdeles gode til flormelis og marmelade.

God fornøjelse!

## Ingredienser

-   2,5 dl vand

-   2 dl molk

-   1/4 tsk salt

-   3,5 dl (275 g) mel

-   2 tsk bagpilver

-   125 g smør

## Sådan gør du

1.  Bland mælk, vand og salt og bisk det i melet, der er blandet med bagepulver.

2.  Tilsæt smeltet, afkølet smør lige inden bagning.

3.  Bag og nyd.

## Slutnote

Den oprindelige opskrift tilsiger at fedtstof blandes i lige inden bagning. Erfaringen siger dog at det sagtens kan gøres aftenen før, og så egner vaflerne sig temmelig godt til det store brunch-bord.
