---
title: Rugbrød
lang: da
date: last-modified
description: Vores hverdagsrugbrød. Det er blevet en vane, så det virker!
categories: 
  - Bagværk
  - Brød
---

Vi er glade for at bage, og særligt rugbrød er lækkert som hjemmebag. Her er opskriften, som vi bruger. Den er overkommelig og, men kræver at man tænker sig lidt om i god tid.

## Dag 1

Tag din surdej ud og fodr den. [Se her for gode råd.](https://andreas.gdamsbo.dk/food/surdej.html)

## Dag 2

-   175 g surdej (ca. 1½ dl)
-   15 g salt (2 spsk)
-   1 liter vand, koldt
-   400 g skårne rugkerner
-   200 g groft hvede-/speltmel
-   375 g rugmel

Røres sammen i en stor skål (5 L). Tildækkes og står ved stuetemperatur i 12-24 timer.

-   450 g skårne rugkerner
-   Evt. 100 g mandler eller hasselnødder, eller 1 dl boghvede, amarant eller chia

Sættes i blød med rigeligt vand 12-36 timer.

## Dag 3

Dejen fra Dag 2 samt drænede, udblødte rugkerner (og nødder/frø) blandes.

Desuden tilsættes følgende:

-   5 dl frø (fx ligelig fordeling af hørfrø, sesam, solsikke- og græskarkerner)
-   1-2 spsk honning (kan røres ud i øl)
-   1 øl (33 cl, gerne hvidtøl eller anden mørk øl, men det kommer sig ikke så nøje)
-   Ca 4 dl rugmel til rette konsistens.

Det hele røres godt sammen. Det skal have en tyk, sej klistret konsistens og fordeles i 3 smurte rugbrødsforme der rummer 2 liter (eller 2 forme á 2-3 liter). Glat dejen.

Lad nu brødene hæve under et fugtigt viskestykke indtil dejen når lidt op over kanten (1-3 timer). Inden de bages, brug da en våd strikkepind eller lignende til at prikke huller i brødene (ca. 30 i hver), så der ikke opstår luftlommer. Bages med konventionel varme ved 180°C i 1 ½ time. For en blød skorpe lægges brødene i plastposer umiddelbart efter bagning. Egner sig til at fryse ned, men vent to døgn. Så smuldrer brødet ikke så meget når det skæres efter optøning.

Tip: rør ca 2 spsk mørk maltsirup i dejen på dag to. Giver mere smag og farve.
