---
title: Rugbrødsopskrift til træramme
lang: da
date: 2024-06-21
author: Andreas
formats: 
  - html: default
  - docx: default
description: Vi har skiftet de gamle brødforme ud med trærammer. Rugbrødsopskriften er let revideret. Det er blevet en vane, så det virker!
categories: 
  - Bagværk
  - Brød
---

Vi har købt tre trærammer fra aarhusianske Kunst og Køkkentøj (de forhandles fra Aurion og produceres på REVA i Herning, hvor [TV MV var forbi for nogle år siden](https://www.tvmidtvest.dk/fast-arbejde/fast-arbejde-fra-reva)) for at undgå metalforme med belægning. Rammerne kan lige stå ved siden af hinanden i ovnen, men har skullet have en helt flad plade at stå på. John-smed har hjulpet, tak for det!

Vores brød blev dog ved at hænge i formene, så vi har revideret opskriften primært ved at tilsætte mere mel for at opnå en lidt fastere dej.

Den oprindelige opskrift [finder du her](https://fam.gdamsbo.dk/food/rugbrød.html).

## Dag 1

Tag din surdej ud og fodr den. [Se her for gode råd.](https://fam.gdamsbo.dk/food/surdej.html)

## Dag 2

- [ ] 175 g surdej (ca. 1½ dl)
- [ ] 30 g salt
- [ ] 1 liter koldt vand
- [ ] 400 g skårne rugkerner
- [ ] 600 g rugmel

Røres sammen i en stor skål (5 L). Tildækkes og står ved stuetemperatur i 12-24 timer.

- [ ] 300 g skårne rugkerner
- [ ] 50-100 g surdej (passer for det meste med resten)
- [ ] Evt. ca 100 g mandler, hasselnødder, boghvede, amarant, chia, quinoa eller lignende.

Sættes i blød med rigeligt vand 12-36 timer.

## Dag 3

Dejen fra Dag 2 samt drænede, udblødte rugkerner (og nødder/frø) blandes.

Desuden tilsættes følgende:

- [ ] 4 dl frø (fx sesam, solsikke- og græskarkerner i forholdet 1:2:1)
- [ ] 1 spsk honning (kan røres ud i øl)
- [ ] 1 øl (33 cl, gerne hvidtøl eller anden mørk øl, men det kommer sig ikke så nøje)
- [ ] Ca 9 dl rugmel til rette konsistens.
- [ ] Evt. 2 spsk mørk maltsirup (Giver mere smag og farve)

Det hele røres godt sammen. Det skal have en tyk, sej klistret konsistens og fordeles i 3 smør-smurte trærammer der rummer 2 liter. Glat dejen.

Lad nu brødene hæve under et fugtigt viskestykke indtil dejen når lidt op over kanten (1-4 timer). Inden de bages, brug da en våd strikkepind eller lignende til at prikke huller i brødene (ca. 30 i hver), så større luftlommer punkteres.

Bages med konventionel varme ved 180°C i 1 time og 45 minutter.

Efter bagning fjernes rammerne og brødene skal køle noget af inden de lægges i plasticposer.

Vi plejer at kunne spise de tre brød i løbet af en uges tid. De holder sig længere i køleskabet, men bliver noget tørre og hårde. Egner sig også til at fryse ned, men vent to døgn. Så smuldrer brødet ikke så meget når det skæres efter optøning.
